[package]
name = "soliloquy"
version = "0.1.7"
authors = ["Spalynx <Spalynx@gmail.com>"]

readme = "README.md"
keywords = ["soliloquy", "nes", "Nintendo", "Entertainment", "System", "Emulator"]
license = "WTFPL2"

publish = false

[dependencies]